Repository LikeLion-at-DGU/2024_fall_festival_front, pull requests merged in 2024-09, with the labels that each got.

#8 [Feature] 축제사이트 초기 환경 구축
  index.html
  jsconfig.json
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/assets/fonts/AppleSDGothicNeoB.ttf
  src/assets/fonts/AppleSDGothicNeoH.ttf
  src/assets/fonts/AppleSDGothicNeoL.ttf
  src/assets/fonts/AppleSDGothicNeoT.ttf
  src/assets/fonts/AppleSDGothicNeoUL.ttf
  src/assets/react.svg
  src/index.css
  src/layout/DefaultLayout.jsx
  src/main.jsx
  src/pages/main/MainPage.jsx
  src/pages/main/MainPage.styled.js
  src/router.jsx
  src/styles/global.js
  src/styles/theme.js
  vercel.json
  vite.config.js
Labels: ✨ Feature, 🍂 세호

#12 [Design] #9 - 공연페이지 초기세팅 css수정
  src/pages/performance/Styled.jsx
  src/pages/performance/performanceslide/Styled.jsx
Labels: 🎨 Design, 🍂 동건

#17 [Feature] #3 공연페이지 BottomTimeSlot 컴포넌트 구현
  src/assets/fonts/AppleSDGothicNeoM.ttf
  src/assets/fonts/AppleSDGothicNeoR.ttf
  src/assets/images/locationIcon.svg
  src/components/performanceP/StarTimeTable/BottomTimeSlot.jsx
  src/components/performanceP/StarTimeTable/StarTimeTable.jsx
  src/components/performanceP/StarTimeTable/TimeSlot.jsx
  src/components/performanceP/StarTimeTable/styled.js
  src/components/performanceP/SubTitle/styled.js
  src/components/performanceP/starBar/StarBar.jsx
  src/components/performanceP/starBar/styled.js
  src/components/performanceP/timeTable/styled.js
  src/constant/TimeTable/data.js
  src/styles/global.js
  src/styles/theme.js
Labels: ✨ Feature, 🎨 Design, 🍂 채민

#22 [Feature] #11 - 공연페이지 슬라이드,축제열기 구현
  package-lock.json
  package.json
  src/assets/images/Fire.svg
  src/assets/images/ping.svg
  src/components/performanceP/fire/Fire.jsx
  src/components/performanceP/fire/Styled.jsx
  src/components/performanceP/performanceslide/PerformanceSlide.jsx
  src/components/performanceP/performanceslide/Styled.jsx
  src/components/performanceP/slide/Slide.jsx
  src/components/performanceP/slide/SlideContents.jsx
  src/components/performanceP/slide/Styled.jsx
  src/constant/TimeTable/data2.js
  src/pages/performance/PerformancePage.jsx
  src/pages/performance/performanceslide/PerformanceSlide.jsx
  src/pages/performance/performanceslide/Styled.jsx
Labels: ✨ Feature, 🎨 Design, 🍂 동건

#23 [Fix] #11 - Slide.jsx 변수정의 오류수정
  src/components/performanceP/slide/Slide.jsx
Labels: 🛠️ Fix, 🍂 동건

#19 Feature #7 공지 페이지 구현
  package-lock.json
  package.json
  src/assets/images/instaIcon.png
  src/assets/images/instaIcon.svg
  src/components/notice/MainNotice/MainNotice.jsx
  src/components/notice/MainNotice/MainStyle.js
  src/components/notice/MainNotice/NoticeItem.jsx
  src/components/notice/MainNotice/itemstyle.js
  src/components/notice/NoticeList/ListBox.jsx
  src/components/notice/NoticeList/ListBoxStyle.js
  src/components/notice/NoticeList/NoticeList.jsx
  src/components/notice/NoticeList/noticeStyle.js
  src/components/notice/Popup/Popup.jsx
  src/components/notice/Popup/popupstyle.js
  src/pages/notice/NoticePage.jsx
  src/pages/notice/NoticePagestyle.js
  src/router.jsx
Labels: ✨ Feature, 🎨 Design, 🛠️ Fix, 🍂 근우

#24 [Feature] #21 개발자정보 페이지 구현
  src/assets/images/LinkImg.svg
  src/assets/images/Logo.png
  src/assets/images/formlink.svg
  src/assets/images/강근우.jpg
  src/assets/images/김민기.jpg
  src/assets/images/김지우.png
  src/assets/images/김지현.jpg
  src/assets/images/김진우.jpg
  src/assets/images/박서현.jpg
  src/assets/images/박선우.jpg
  src/assets/images/박세라.jpg
  src/assets/images/박세호.jpg
  src/assets/images/박채현.jpg
  src/assets/images/오태준.png
  src/assets/images/이동건.jpg
  src/assets/images/임수빈.jpg
  src/assets/images/임현우.jpg
  src/assets/images/전효준.jpg
  src/assets/images/정지윤.jpg
  src/assets/images/조성현.jpg
  src/assets/images/최민.jpg
  src/assets/images/하채민.jpg
  src/assets/images/한지은.jpg
  src/assets/images/황채현.jpg
  src/components/about/AboutCard/AboutCard.jsx
  src/components/about/AboutCard/styled.js
  src/components/about/LikeLionLink/LikeLionLink.jsx
  src/components/about/LikeLionLink/styled.js
  src/components/about/Review/Review.jsx
  src/components/about/Review/styled.js
  src/pages/about/AboutPage.jsx
  src/pages/about/AboutPage.styled.js
  src/router.jsx
Labels: ✨ Feature, 🎨 Design, 🍂 민

#26 [Feature]/#3 - 스타 디테일 컴포넌트 구현
  src/assets/images/X_Icon.svg
  src/components/performanceP/StarDetail/StarDetail.jsx
  src/components/performanceP/StarDetail/styled.js
  src/components/performanceP/StarTimeTable/StarTimeTable.jsx
  src/components/performanceP/StarTimeTable/TimeSlot.jsx
  src/components/performanceP/StarTimeTable/styled.js
  src/components/performanceP/starBar/StarBar.jsx
  src/components/performanceP/starBar/styled.js
  src/components/performanceP/timeTable/TimeTable.jsx
  src/components/performanceP/timeTable/styled.js
  src/constant/StarDetail/data.js
  src/constant/TimeTable/data.js
  src/pages/performance/PerformancePage.jsx
Labels: ✨ Feature, 🎨 Design, 🍂 채민
