Repository LikeLion-at-DGU/2024_fall_festival_front, pull requests merged in 2024-10, with the labels that each got.

#30 [Feature] #4 - 카카오맵 API 디자인
  src/assets/images/LinenowLogo.png
  src/assets/images/LinenowLogo_nu.png
  src/assets/images/nonselect_GI.png
  src/assets/images/nonselect_JU.png
  src/assets/images/select_GI.png
  src/assets/images/select_JU.png
  src/boothdata/Boothdata.js
  src/pages/booth/BoothPage.jsx
  src/pages/booth/Styled.js
Labels: ✨ Feature, 🍂 태준

#32 [Design] #4 전체 디자인 수정
  src/assets/images/Mainicon.png
  src/assets/images/leaf/leaf1.png
  src/assets/images/leaf/leaf2.png
  src/assets/images/leaf/leaf3.png
  src/components/topBar/TopBar.jsx
  src/components/topBar/styled.js
  src/pages/booth/BoothPage.jsx
  src/pages/booth/Styled.js
Labels: 🎨 Design, 🍂 태준

#36 [Feature] #35 - Google 애널리틱스 연결
  index.html
  package-lock.json
  package.json
  src/router.jsx
Labels: ✨ Feature, 🍂 세호

#42 [Feature]#27 -부스페이지 API 연결 세팅
  package-lock.json
  package.json
  src/apis/booth.js
  src/apis/boothDetail.js
  src/apis/instance.js
  src/hook/useBooth.js
  src/hook/useBoothDetail.js
  src/pages/booth/BoothPage.jsx
  src/pages/performance/PerformancePage.jsx
  src/router.jsx
Labels: 📚 API, 🍂 채민

#48 [Feature] #38 - 모달팝업 개발
  src/assets/images/X.svg
  src/components/modal/Modal.jsx
  src/components/modal/Styled.js
  src/components/performanceP/starBar/StarBar.jsx
  src/components/topBar/TopBar.jsx
  src/pages/booth/BoothPage.jsx
Labels: ✨ Feature, 🎨 Design, 🍂 동건

#51 [Design] #4 카카오맵 디자인 수정
  src/components/topBar/styled.js
  src/pages/booth/BoothPage.jsx
  src/pages/booth/Styled.js
Labels: 🎨 Design, 🍂 태준

#52 [Design] #4 디자인 충돌 병합했습니다
  src/components/modal/Modal.jsx
  src/pages/booth/BoothPage.jsx
Labels: 🎨 Design, 🍂 태준

#55 [Design] #4 카카오맵 API 애니메이션 및 디자인 전체 수정
  src/pages/booth/BoothPage.jsx
  src/pages/booth/Styled.js
Labels: 🎨 Design, 🍂 태준

#54 [Feature]#27 - 부스 디테일 컴포넌트 구현
  src/apis/booth.js
  src/apis/boothDetail.js
  src/assets/images/tabling.svg
  src/components/common/BoothDetail/BoothDetail.jsx
  src/components/common/BoothDetail/styled.js
  src/components/performanceP/StarDetail/StarDeatil.jsx
  src/components/performanceP/StarDetail/styled.js
  src/constant/StarDetail/data.js
  src/hook/useBooth.js
  src/hook/useBoothDetail.js
  src/pages/about/AboutPage.jsx
  src/pages/booth/BoothPage.jsx
  src/router.jsx
Labels: ✨ Feature, 🎨 Design, 🍂 채민

#83 [Feature] #4 카카오맵 현 위치 구현
  src/pages/booth/BoothPage.jsx
  src/pages/booth/Styled.js
Labels: ✨ Feature, 🎨 Design, 🍂 태준

#69 [Chore] #67 - 최종 에러 테스트 진행
  src/apis/booth.js
  src/components/about/Review/Review.jsx
  src/hook/useBooth.js
  src/router.jsx
Labels: 🛠️ Fix, 🍂 세호

#121 [Fix] #120 - 배포폰트 적용오류 수정
  public/fonts/AppleSDGothicNeoB.ttf
  public/fonts/AppleSDGothicNeoH.ttf
  public/fonts/AppleSDGothicNeoL.ttf
  public/fonts/AppleSDGothicNeoM.ttf
  public/fonts/AppleSDGothicNeoR.ttf
  public/fonts/AppleSDGothicNeoT.ttf
  public/fonts/AppleSDGothicNeoUL.ttf
  public/fonts/NanumSquareRoundB.ttf
  public/fonts/NanumSquareRoundEB.ttf
  public/fonts/NanumSquareRoundL.ttf
  public/fonts/NanumSquareRoundOTFB.otf
  public/fonts/NanumSquareRoundR.ttf
  src/styles/global.js
Labels: 🛠️ Fix, 🍂 동건

#127 [FIx] #4 카카오맵 중앙 유지 및 SDK 비동기식 개선
  src/pages/booth/BoothPage.jsx
  src/pages/booth/Styled.js
Labels: 🛠️ Fix, 🍂 태준

#130 [Fix] Feature/#34 검색 기능 초기화 및 오류 메세지
  src/components/searchBar/SearchBar.jsx
  src/pages/booth/BoothPage.jsx
Labels: 🛠️ Fix, 🍂 근우

#132 [Design] #4 디자인 수정
  src/pages/booth/BoothPage.jsx
  src/pages/booth/Styled.js
Labels: 🎨 Design, 🍂 태준

#159 [Fix] #4 부스 선택시 리스트에서도 보이도록
  src/apis/booth.js
  src/apis/instance.js
  src/hook/useBooth.js
  src/hook/useBoothDetail.js
  src/pages/booth/BoothPage.jsx
Labels: 🛠️ Fix, 🍂 태준

#161 [Refactor] #158 - 모달팝업 홈화면으로가기,개발자페이지 모달팝업문제 해결
  src/components/modal/Modal.jsx
  src/pages/about/AboutPage.jsx
Labels: 🎨 Design, 🛠️ Fix, 🍂 동건

#166 refactor: 폼즈 주소 재수정
  src/components/modal/Modal.jsx
Labels: 🛠️ Fix, 🍂 태준

#167 🚀 Deploy
  src/components/modal/Modal.jsx
Labels: 🛠️ Fix, 🍂 태준
